name: Boring maintenance stuff

on:
  schedule:
    - cron: 0 0 1 */2 *
  workflow_dispatch:

jobs:
  update_packages:
    runs-on: windows-2019
    
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
    - name: Checkout Code
      uses: actions/checkout@v1
      
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
     
    - name: Restore NuGet Packages
      run: nuget restore BepInEx.LoveMachine.sln
    
    - name: Update NuGet Packages
      run: nuget update BepInEx.LoveMachine.sln
    
    - name: Restore NuGet Packages again because why not
      run: nuget restore BepInEx.LoveMachine.sln

    - name: Build and Publish
      run: msbuild BepInEx.LoveMachine.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: Update NuGet dependencies
        committer: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
        author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
        branch: package-update
        base: mastur
        delete-branch: true
        title: 'Update NuGet dependencies'
        body: Bringing the latest and greatest of everything.
        assignees: Sauceke
        reviewers: Sauceke
