name: Manual release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true

jobs:
  release:
    runs-on: windows-2019
    timeout-minutes: 5
    
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v1
    
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
     
    - name: Restore NuGet Packages
      run: nuget restore BepInEx.LoveMachine.sln
 
    - name: Build and Publish
      run: msbuild BepInEx.LoveMachine.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile /p:Version=${{ github.event.inputs.version }}
    
    - name: Zip artifacts
      run: |
        powershell Compress-Archive -Path bin/LoveMachine.KK/BepInEx -DestinationPath LoveMachine_for_Koikatsu.zip
        powershell Compress-Archive -Path bin/LoveMachine.KKS/BepInEx -DestinationPath LoveMachine_for_Koikatsu_Sunshine.zip
        powershell Compress-Archive -Path bin/LoveMachine.HS2/BepInEx -DestinationPath LoveMachine_for_Honey_Select_2.zip
        powershell Compress-Archive -Path bin/LoveMachine.PH/BepInEx -DestinationPath LoveMachine_for_PlayHome.zip
        powershell Compress-Archive -Path bin/LoveMachine.AGH/BepInEx -DestinationPath LoveMachine_for_Houkago_Rinkan_Chuudoku.zip
        powershell Compress-Archive -Path bin/LoveMachine.OA/BepInEx -DestinationPath LoveMachine_for_Our_Apartment.zip

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.event.inputs.version }}
        release_name: Release v${{ github.event.inputs.version }}
        body: write the changelog you lazy fuk
        draft: true
        prerelease: false
        
    - name: Upload All Plugins
      uses: alexellis/upload-assets@0.2.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        asset_paths: '["LoveMachine_*.zip"]'
