name: Manual release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true

jobs:
  release:
    runs-on: windows-2019
    
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code
    
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
     
    - name: Restore NuGet Packages
      run: nuget restore KK_ButtPlugin.sln
 
    - name: Build and Publish
      run: msbuild KK_ButtPlugin.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile
    
    - name: Zip artifacts
      run: |-
        powershell New-Item -Path BepInEx/plugins/KK_ButtPlugin -ItemType Directory;
        powershell Copy-Item -Path bin/* -Destination BepInEx/plugins/KK_ButtPlugin;
        powershell Compress-Archive -Path BepInEx -DestinationPath ButtPlugin.zip

    - name: Generate changelog
      id: generate_changelog
      uses: metcalfc/changelog-generator@v0.4.4
      with:
        myToken: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.version }}
        release_name: Release ${{ github.event.inputs.version }}
        body: ${{ steps.generate_changelog.outputs.changelog }}
        draft: true
        prerelease: false
        
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./ButtPlugin.zip
        asset_name: ButtPlugin.zip
        asset_content_type: application/zip
