name: Manual release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true

jobs:
  release:
    runs-on: windows-2019
    timeout-minutes: 5
    
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v1
    
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
     
    - name: Restore NuGet Packages
      run: nuget restore BepInExButtPlugin.sln
 
    - name: Build and Publish
      run: msbuild BepInExButtPlugin.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile /p:Version=${{ github.event.inputs.version }}
    
    - name: Zip artifacts
      run: |-
        powershell New-Item -Path BepInEx/plugins/KK_ButtPlugin -ItemType Directory;
        powershell Copy-Item -Path bin/ButtPlugin.KK/* -Destination BepInEx/plugins/KK_ButtPlugin;
        powershell Compress-Archive -Path BepInEx -DestinationPath KK_ButtPlugin.zip
        powershell Remove-Item -Path BepInEx/plugins/KK_ButtPlugin -Recurse
        powershell New-Item -Path BepInEx/plugins/HS2_ButtPlugin -ItemType Directory;
        powershell Copy-Item -Path bin/ButtPlugin.HS2/* -Destination BepInEx/plugins/HS2_ButtPlugin;
        powershell Compress-Archive -Path BepInEx -DestinationPath HS2_ButtPlugin.zip
        powershell Remove-Item -Path BepInEx/plugins/HS2_ButtPlugin -Recurse
        powershell New-Item -Path BepInEx/plugins/KKS_ButtPlugin -ItemType Directory;
        powershell Copy-Item -Path bin/ButtPlugin.KKS/* -Destination BepInEx/plugins/KKS_ButtPlugin;
        powershell Compress-Archive -Path BepInEx -DestinationPath KKS_ButtPlugin.zip
        powershell Remove-Item -Path BepInEx/plugins/KKS_ButtPlugin -Recurse

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.event.inputs.version }}
        release_name: Release v${{ github.event.inputs.version }}
        body: write the changelog you lazy fuk
        draft: true
        prerelease: false
        
    - name: Upload Koikatsu Plugin
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./KK_ButtPlugin.zip
        asset_name: ButtPlugin_for_Koikatsu.zip
        asset_content_type: application/zip

    - name: Upload Koikatsu Sunshine Plugin
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./KKS_ButtPlugin.zip
        asset_name: ButtPlugin_for_Koikatsu_Sunshine.zip
        asset_content_type: application/zip

    - name: Upload Honey Select 2 Plugin
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./HS2_ButtPlugin.zip
        asset_name: ButtPlugin_for_Honey_Select_2.zip
        asset_content_type: application/zip
