name: Manual release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true

jobs:
  release:
    runs-on: windows-2019
    timeout-minutes: 5
    
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v1

    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
     
    - name: Download Inno Setup
      run: |
          mkdir C:\innosetup
          curl -o C:\innosetup\innosetup.exe https://files.jrsoftware.org/is/6/innosetup-6.2.0.exe
          C:\innosetup\innosetup.exe /VERYSILENT /NORESTART /ALLUSERS
    
    - name: Restore NuGet Packages
      run: nuget restore LoveMachine.sln
 
    - name: Build and Publish
      run: msbuild LoveMachine.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile /p:Version=${{ github.event.inputs.version }}
  
    - name: Build Installer
      run: |
        cd Installer
        curl -o .\BepInEx32.zip https://github.com/BepInEx/BepInEx/releases/download/v5.4.18/BepInEx_x86_5.4.18.0.zip
        curl -o .\BepInEx64.zip https://github.com/BepInEx/BepInEx/releases/download/v5.4.18/BepInEx_x64_5.4.18.0.zip
        powershell Get-FileHash .\BepInEx32.zip
        7z x .\BepInEx32.zip -oBepInEx32
        7z x .\BepInEx64.zip -oBepInEx64
        & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" InstallScript.iss
        cd ..

    - name: Zip artifacts
      run: |
        mkdir assets
        7z a assets/LoveMachine_for_Koikatsu.zip bin/LoveMachine.KK/BepInEx
        7z a assets/LoveMachine_for_Koikatsu_Sunshine.zip bin/LoveMachine.KKS/BepInEx
        7z a assets/LoveMachine_for_Honey_Select_2.zip bin/LoveMachine.HS2/BepInEx
        7z a assets/LoveMachine_for_PlayHome.zip bin/LoveMachine.PH/BepInEx
        7z a assets/LoveMachine_for_Houkago_Rinkan_Chuudoku.zip bin/LoveMachine.AGH/BepInEx
        7z a assets/LoveMachine_for_Our_Apartment.zip bin/LoveMachine.OA/BepInEx
        copy Installer/bin/LoveMachineInstaller.exe assets/LoveMachineInstaller.exe

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.event.inputs.version }}
        release_name: Release v${{ github.event.inputs.version }}
        body: write the changelog you lazy fuk
        draft: true
        prerelease: false

    - name: Upload Release Assets
      id: upload-release-assets
      uses: dwenegar/upload-release-assets@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.create_release.outputs.id }}
        assets_path: assets
