name: Manual release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true

jobs:
  release:
    runs-on: windows-2019
    timeout-minutes: 5
    
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      INNO_SETUP_URL: https://files.jrsoftware.org/is/6/innosetup-6.2.0.exe
      BEPINEX_32_URL: https://github.com/BepInEx/BepInEx/releases/download/v5.4.18/BepInEx_x86_5.4.18.0.zip
      BEPINEX_64_URL: https://github.com/BepInEx/BepInEx/releases/download/v5.4.18/BepInEx_x64_5.4.18.0.zip
      BEPINEX_CONF_MGR_URL: https://github.com/BepInEx/BepInEx.ConfigurationManager/releases/download/v16.4/BepInEx.ConfigurationManager_v16.4.zip
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v1

    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
     
    - name: Download Inno Setup
      run: |
        Invoke-WebRequest -Uri ${{env.INNO_SETUP_URL}} -OutFile .\innosetup.exe
        & .\innosetup.exe /VERYSILENT /NORESTART /ALLUSERS
    
    - name: Restore NuGet Packages
      run: nuget restore LoveMachine.sln
 
    - name: Build and Publish
      run: msbuild LoveMachine.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile /p:Version=${{ github.event.inputs.version }}
  
    - name: Download BepInEx
      run: |
        cd Installer
        Invoke-WebRequest -Uri ${{env.BEPINEX_32_URL}} -OutFile .\BepInEx32.zip
        Invoke-WebRequest -Uri ${{env.BEPINEX_64_URL}} -OutFile .\BepInEx64.zip
        Invoke-WebRequest -Uri ${{env.BEPINEX_CONF_MGR_URL}} -OutFile .\BepInEx.ConfigurationManager.zip
        Expand-Archive -Path .\BepInEx32.zip -DestinationPath .\BepInEx32
        Expand-Archive -Path .\BepInEx64.zip -DestinationPath .\BepInEx64
        Expand-Archive -Path .\BepInEx.ConfigurationManager.zip -DestinationPath .\BepInEx32
        Expand-Archive -Path .\BepInEx.ConfigurationManager.zip -DestinationPath .\BepInEx64
        cd ..

    - name: Build Installer
      run: |
        cd Installer
        & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" InstallScript.iss
        cd ..

    - name: Zip artifacts
      run: |
        mkdir assets
        Compress-Archive -Path bin/LoveMachine.KK/BepInEx -DestinationPath assets/LoveMachine_for_Koikatsu.zip
        Compress-Archive -Path bin/LoveMachine.KKS/BepInEx -DestinationPath assets/LoveMachine_for_Koikatsu_Sunshine.zip
        Compress-Archive -Path bin/LoveMachine.HS2/BepInEx -DestinationPath assets/LoveMachine_for_Honey_Select_2.zip
        Compress-Archive -Path bin/LoveMachine.PH/BepInEx -DestinationPath assets/LoveMachine_for_PlayHome.zip
        Compress-Archive -Path bin/LoveMachine.AGH/BepInEx -DestinationPath assets/LoveMachine_for_Houkago_Rinkan_Chuudoku.zip
        Compress-Archive -Path bin/LoveMachine.OA/BepInEx -DestinationPath assets/LoveMachine_for_Our_Apartment.zip
        copy Installer/bin/LoveMachineInstaller.exe assets/LoveMachineInstaller.exe

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.event.inputs.version }}
        release_name: Release v${{ github.event.inputs.version }}
        body: write the changelog you lazy fuk
        draft: true
        prerelease: false

    - name: Upload Release Assets
      id: upload-release-assets
      uses: dwenegar/upload-release-assets@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.create_release.outputs.id }}
        assets_path: assets
